site_name: Kobalt
site_description: A lightweight Kotlin wrapper for JDA
site_url: https://kobalt.readthedocs.io
repo_url: https://github.com/Mstr0A/Kobalt
repo_name: Mstr0A/Kobalt

theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Guides:
      - Bots: bots.md
      - Commands: commands.md
      - Event Waiter: event-waiter.md
      - Extending KBot: extending-kbot.md
  - Changelog: changelog.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - admonition
  - tables
